apiVersion: apps/v1
kind: Deployment
metadata:
  name: mybatis-sub-service-deployment
  namespace: mybatis
  labels:
    app: mybatis-sub-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mybatis-sub-service
  template:
    metadata:
      labels:
        app: mybatis-sub-service
    spec:
      containers:
        - name: mybatis-sub-service
          image: test/mybatis-sub-service
          imagePullPolicy: Never
          ports:
            - containerPort: 9091
          env:
            - name: RABBITMQ_USER
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: rabbitmq-user
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: rabbitmq-password
---
apiVersion: v1
kind: Service
metadata:
  name: mybatis-sub-service-service
  namespace: mybatis
spec:
#  type: ClusterIP
  type: NodePort
  selector:
    app: mybatis-sub-service
  ports:
    - protocol: TCP
      port: 9091
      targetPort: 9091
      nodePort: 30501